### ISSUE TITLE
Disabled ufw

### ISSUE THREAD

**Issue by dot-slash** [BrainfuckSec/kalitorify#1]
Is there a cleaner way to enable the transparent proxying without completely disabling ufw? This potentially leaves ports open whilst the script is enabled.

Adding the following lines during the startup (after the other iptables rules) ensures slightly better security:

iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT  
iptables -A INPUT -i lo -j ACCEPT  
iptables -A INPUT -j DROP  

iptables -P INPUT DROP  
iptables -P FORWARD DROP  
iptables -P OUTPUT DROP

**Comment by dot-slash** [comment]
I'm working on a similar project: https://github.com/dot-slash/torproxy

**Comment by BrainfuckSec** [comment]
Hi dot-slash, really thanks for the advice, I will insert this rules in the next version, soon the update.
Good work for your project!
