### ISSUE TITLE
HTTP request error!

### ISSUE THREAD

**Issue by johnvega26** [brainfucksec/kalitorify#14]
Checking your public IP, please wait...
[ failed ] curl: HTTP request error!
Please check your network settings.

**Comment by brainfucksec** [comment]
Added another domain for check the public IP: 
https://github.com/brainfucksec/kalitorify/commit/b808d227a6246db7ab20513c0490179c2472d805

Try now.

**Comment by brainfucksec** [comment]
Since it’s been three months, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
