### ISSUE TITLE
Check Tor network settings Your system is not using Tor!

### ISSUE THREAD

**Issue by ghost** [brainfucksec/kalitorify#19]
I have 2 issues: 
1. i get an error but still my IP is changed, so it seems work, although i have this error:
Check Tor network settings
Your system is not using Tor!
2. the IP shown in Kalitorify is different then the IP in DNSleak website.

**Comment by brainfucksec** [comment]
Hi @juistevorm, In the program, the external IP check function uses curl, probably this is a temporary problem concerning http requests, so try these steps:

1. Start kalitorify: `kalitorify --tor`
2. If this error occurs again the error restarts program and check status with:
    - `kalitorify --restart`
    - `kalitorify --status`

In order to give a more precise answer I need information on the network configuration, so you should use the template for the issues.

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.

**Comment by CyberKrypts** [comment]
i got like [!] Your system is not using Tor when i try to use --restarts or status it shows evrything ok again if user --tor getting same issue [!] Your system is not using Tor its a safe sign ??? i tried so many days

**Comment by nikhil0162** [comment]
If above things doesn't work then try to enable "use bridges" in tor settings -> tor or type ```about:preferences#tor``` in your tor browser address bar

**Comment by MrOffSec** [comment]
Hi, I just came along this problem myself.I found another solution. I also opened a seperate [issue](https://github.com/brainfucksec/kalitorify/issues/64) for this.

**Comment by Masukashan** [comment]
i started tor just so its open and running in a terminal 
and then i restarted tor services in a second terminal  
after that  i stopped the tor services  and run "kalitoryfi -t" again and it worked .
i dont know why  it wanted me to have open and running the tor but it wanted me to do so
for proxychains too in a separate terminal . I dont know if its the same thing 
but whenever im trying to use tor for something i go through this cycle .
