### ISSUE TITLE
curl: HTTP request error!

### ISSUE THREAD

**Issue by c20xh2** [brainfucksec/kalitorify#2]
DNS resolution not working avec running 
`
sudo kalitorify --start
`
Infos:

`Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
`
I'm able to ping IP but not domain names.

I'm running behind a PiHole, don't know if that can be a problem

**Comment by brainfucksec** [comment]
If you use PiHole you are under VPN, you can't use Transparent Proxy and OpenVPN at the same time.
Stop PiHole, restart the network interface then start kalitorify. 

If you need a route vpn > transparent proxy through tor, you have to start openvpn from yous host then to set up a virtual machine with kali linux installed and start kalitorify from the virtual machine.

host system (with openvpn) > guest system (with kali linux and kalitorify)

**Comment by c20xh2** [comment]
Thanks for the info brainfucksec, have a good one
