### ISSUE TITLE
How to update Kalitorify???

### ISSUE THREAD

**Issue by anggisaja** [brainfucksec/kalitorify#21]
How to update kalitorify???

**Comment by bohemian9485** [comment]
git pull?

**Comment by brainfucksec** [comment]
Hi @anggisaja, kalitorify was born as a git package, as such it receives relatively frequent updates, to update the git packages there are several methods, the fastest method is to save the kalitorify folder on the computer and manually check if there are updates with the `git pull` command.
Example:

```bash
cd ~/home/user/kalitorify
git pull
```

After that re-run the installer: https://github.com/brainfucksec/kalitorify#install
More info about the `git pull` command: https://git-scm.com/docs/git-pull
