### ISSUE TITLE
Can't connect to the internet after(maybe broken) install

### ISSUE THREAD

**Issue by Asdrubale2** [brainfucksec/kalitorify#22]
After installing kalitorify v1.17.1 on my 2019.x kali release, it's been impossible for me to have internet access at any level on my os. Not from terminal nor browsers or software center.

When typing kalitorify -t
I get:
cp: cannot stat '/et /resolv.conf' : no such file or directory
[Failed] cant copy resolv.conf to the backup directory

For kalitorify -r
I get 
[Failed] curl: HTTP request error

For kalitorify -c
I get no error messages but still can't access Internet

For kalitorify -s
Tor service is not running

I've installed sooner openvpn and protonvpn. And it was working.

**Comment by Asdrubale2** [comment]
Solved:
/etc/resolv.conf has been deleted so i created a new one with text editor.
Inside I've put:
search duckduckgo.com
nameserver 208.67.222.222
nameserver 208.67.220.220
nameserver 8.8.8.8
nameserver 8.8.4.4

Saved, and it works now. I did never open resolv.conf so i didn't know what to put in it. If I've screwed up in some way let me know and I'll fix it

**Comment by brainfucksec** [comment]
Hi @Asdrubale2, thanks for the report.
kalitorify on startup copies the original resolv.conf file to the backup directory `/opt/kalitorify/backups` then it writes the `nameserver 127.0.0.1`on current file to allow connection with the Tor network.
When the program is terminated the resolv.conf file is restored to its original state.
For more information about ` /etc/resolv.conf` file I invite you to read here:

https://en.wikipedia.org/wiki/Resolv.conf
https://wiki.debian.org/resolv.conf

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
