### ISSUE TITLE
Error in running the script

### ISSUE THREAD

**Issue by najum98** [brainfucksec/kalitorify#24]
I have just installed the script and its dependencies, whenever I try to run the script using **./kalitorify.sh -t** it gives me the error that Your system us not using tor whereas I have the latest tor installed on my pc and I have tried manually starting the tor service as well but of no avail

**Comment by brainfucksec** [comment]
Hi @najum98, I need more information, please use the template: https://github.com/brainfucksec/kalitorify/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
