### ISSUE TITLE
Your system is not using Tor!

### ISSUE THREAD

**Issue by made98** [brainfucksec/kalitorify#27]
**Describe the bug**
When i run ```kalitorify -t``` i get *Your system is not using Tor!* message

**Program error message**
Your system is not using Tor!

**Shell used**
bash

**Comment by brainfucksec** [comment]
Hi @made98.
* You rebooted the system after installing the program?
* You get this message even after trying with the `--restart` command?

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.

**Comment by mrhili** [comment]
it happen for me too i have the latest kali Linux in a virtualbox machine I did the restar and then I check with the -s and I get YOUR SYSTEM IS NOT USING TOR

**Comment by mrhili** [comment]
I put the comand 8 time and still hapenning , should I do something before lunching kalitorify ? like whonix or something else ?
