### ISSUE TITLE
Error in UFW check

### ISSUE THREAD

**Issue by djeraseit** [brainfucksec/kalitorify#28]
Regex issue on line 143
`if ufw status | grep -q active$; then`

This will catch "inactive" as well as "active".

So even if our firewall is currently "inactive" the script will try to disable it.

**Comment by brainfucksec** [comment]
Hi @djeraseit, the functions related to ufw are from a few years ago, but if I remember correctly I had performed several tests, however, I will check that function, thanks a lot for reporting.

**Comment by brainfucksec** [comment]
It should be fixed, you can see the details of the program code in the last commit:
https://github.com/brainfucksec/kalitorify/commit/6ffe2625dc17e7f8075c737d6c51dd4d0be8f5c1

Thank you again for your help @djeraseit your report was very useful :)
