### ISSUE TITLE
Your system is not using Tor!

### ISSUE THREAD

**Issue by et90d** [brainfucksec/kalitorify#29]
**Describe the bug**
On VirtualBox Kali Linux if i start kalitorify (`kalitorify -t`) without MAC change 
all ok. 

But if i try to change Mac 
```
ifconfig eth0 down
macchanger -r eth0
ifconfig eth0 up 
kalitorify -t
```
i got an error:

> Check Tor network settings
> [!] Your system is not using Tor! 

i try to run `kalitorify -r` and no result:

> ==> Restart Tor service and change IP
> [ ok ] Tor Exit Node changed
> ==> Checking your public IP, please wait...

**Program error message**

> Check Tor network settings
> [!] Your system is not using Tor!

**Other network proxies/firewalls or DNS applications installed**
no

**Shell used**
bash

**Additional context**
After this i need to reboot Kali to start kalitorify without issues.
If i didn't change MAC - all working ok.

**Comment by brainfucksec** [comment]
Hi @et90d, thanks for your report.
I will be able to help you after running some tests to see if the problem is related to the program or to your configuration.

**Comment by et90d** [comment]
Hi @brainfucksec, thanks you for reply.
Please let me know if you need additional information about my system configuration.

**Comment by brainfucksec** [comment]
Try to manage the interface with the `ip` commands :
`ip link set eth0 down`
`ip link set eth0 up`

**Comment by et90d** [comment]
No. Not on Raspberry Pi. Macbook + Virtualbox
Tried `ip` commands. All the same.

**Comment by brainfucksec** [comment]
So, do you use Kali Linux on VirtualBox?
VirtualBox does not support MAC spoofing from command line, but it can be changed from the settings:

[VirtualBox - Macchanger and internet issues](https://forums.virtualbox.org/viewtopic.php?t=83858)

**Comment by et90d** [comment]
> So, do you use Kali Linux on VirtualBox?

yes. Ok got it. Thank you so much!

**Comment by Banginpadr** [comment]
I'm having this same problem but in using kali in a windows partition. I'm using kali rolling

**Comment by MyKal123** [comment]
how do you fix that in raspberry pi? and i do not know about ip command

**Comment by conceptuando** [comment]
Do you know if there is a solution for this problem that I also have with Kali on WSL2? Thanks
