### ISSUE TITLE
Doesn't check for directories existence before attempting to write to it

### ISSUE THREAD

**Issue by Veritas83** [brainfucksec/kalitorify#3]
Backup iptables rules... ./kalitorify.sh line 241: /opt/kalitorify/backups/iptables.backup: No such file or directory

Screen: https://i.gyazo.com/3aed39c067af7f7cb03b5e5b65d0aa64.png

**Comment by Veritas83** [comment]
I see now the makefile would have resolved this had I used it.

**Comment by brainfucksec** [comment]
Yes, if you install the program with 'make install' first, then you have the directories configured. 
Anyway I will add further checks on these directories for avoid errors, thanks for the reporting.
