### ISSUE TITLE
Stuck at "setup new iptables rules" after "kalitorify -t" on Raspberry Pi 4

### ISSUE THREAD

**Issue by cinetube** [brainfucksec/kalitorify#30]
<img width="550" alt="67151562-b507cd80-f2e9-11e9-98f9-64b1c083fd45" src="https://user-images.githubusercontent.com/23441775/67151832-63614200-f2ed-11e9-857a-0f8ba1b65350.png">

Stuck at setup new iptables rules step.

Using Raspberry Pi 4

**Comment by brainfucksec** [comment]
Hi @cinetube on the Raspberry Pi 4 you have to configure the iptables as indicated in the links below:

https://blog.mxard.com/persistent-iptables-on-raspberry-pi-raspbian

https://blog.onetwentyseven001.com/iptables-security-part-ii/

also check this post if it can help you:

[Transparent Proxy not Work on Raspberry Pi 3 #20](https://github.com/brainfucksec/kalitorify/issues/20)

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
