### ISSUE TITLE
everytime i start kalitorify

### ISSUE THREAD

**Issue by learningsomethingnewanduseful** [brainfucksec/kalitorify#31]
sudo kalitorify -t

 _____     _ _ _           _ ___
|  |  |___| |_| |_ ___ ___|_|  _|_ _
|    -| .'| | |  _| . |  _| |  _| | |
|__|__|__,|_|_|_| |___|_| |_|_| |_  |
                                |___| v1.19.1

=[ Transparent proxy through Tor
=[ BrainfuckSec

==> Check default settings
:: Setting file: /etc/tor/torrc...
'/etc/tor/torrc' -> '/usr/share/kalitorify/backups/torrc.backup'
'/usr/share/kalitorify/data/torrc' -> '/etc/tor/torrc'

==> Starting Transparent Proxy
:: Disabling firewall ufw, please wait...
Firewall stopped and disabled on system startup

:: Configure system's DNS resolver to use Tor's DNSPort
'/etc/resolv.conf' -> '/usr/share/kalitorify/backups/resolv.conf.backup'

:: Disable IPv6 with sysctl
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

:: Start Tor service
[ ok ] Tor service started

:: Setup new iptables rules
[ ok ] iptables rules set

==> Check current status of Tor service
[ ok ] Tor service is active

==> Check Tor network settings
[!] Your system is not using Tor!

try another Tor circuit with 'kalitorify --restart'

so i need to restart after every time start kalitorify.. why?

**Comment by brainfucksec** [comment]
Hi @learningsomethingnewanduseful 
I need more details about your setup, please see the [issue template](https://github.com/brainfucksec/kalitorify/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
