### ISSUE TITLE
Leaks when using Nessus

### ISSUE THREAD

**Issue by hybla0** [brainfucksec/kalitorify#32]
@brainfucksec hi
**Describe the bug**
I am having leak issues when running a scan with Nessus : wireshark shows that the packets go directly to the target without passing through tor guard ip.It seems Nessus is able to bypass iptables.

**Program error message**
None

**Screenshots**

**Other network proxies/firewalls or DNS applications installed**
I dont know: it is a clean install of kali linux with only Nessus added

**Shell used**
bash on kali linux 2019.1 vmware image

**Additional context**
Other applications like openvas, nmap go through the tor guard ip and no traffic is detected using 
tcpdump -n -f -p -i eth0 not arp and not host IP.TO.TOR.GUARD

**Comment by brainfucksec** [comment]
Hi @hybla0, I don't use Nessus, so I need some time to understand what happens between this program and the iptables with Tor.
Thank you for the report, I'll try to fix this problem as soon as possible.

**Comment by hybla0** [comment]
@brainfucksec What do you use for vulnerability scanning/assessment?maybe I am using the wrong utility which is incompatible with Kalitorify, I am ok to switch to something cooler if it exists :)

**Comment by brainfucksec** [comment]
@hybla0, generally I don't use frameworks like Nessus, OpenVAS or anything else, but everyone has their own preferences, however here you can find a list of the tools I prefer:

https://www.reddit.com/r/Pentesting/comments/9ondj5/a_good_pentesting_tools_list/

**Comment by brainfucksec** [comment]
Hi @hybla0, I invite you to try Nessus again with the latest update of `kalitorify`

**Comment by ouledzmitli** [comment]
hello , can you please explain to me the difference between kalitorify and nipe ? wich is the best in anonymity ? and how we can use both to scan with Nmap .
