### ISSUE TITLE
Extra shift call causes exit code 1

### ISSUE THREAD

**Issue by ViRb3** [brainfucksec/kalitorify#33]
There's a `shift` call to get rid of the `-t` argument here:
https://github.com/brainfucksec/kalitorify/blob/74b97362e16abc394ece7f384fbb8b3c8710ccce/kalitorify.sh#L569-L574

But also here:
https://github.com/brainfucksec/kalitorify/blob/74b97362e16abc394ece7f384fbb8b3c8710ccce/kalitorify.sh#L598-L601

Since there's nothing else to remove, the command will exit with code 1, which will in turn make the script return error code 1, even though it succeeded. Maybe remove the first `shift` call?

**Comment by brainfucksec** [comment]
Hi @ViRb3, thanks for the report.
You're right, that statement is totally useless.
I am working on updating the program, I will commit as soon as possible

**Comment by brainfucksec** [comment]
@ViRb3, I've eliminated the "extra" shift command.
Thank you very much for your help and for making this program better.
