### ISSUE TITLE
Secure start on boot

### ISSUE THREAD

**Issue by ViRb3** [brainfucksec/kalitorify#34]
Is there any way to securely start kalitorify on boot? Currently, I have created a simple systemd service:
```
[Unit]
Description=kalitorify
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/home/user/kalitorify/kalitorify.sh -t

[Install]
WantedBy=multi-user.target
```

However, there's no error checking and even if everything works, there's still a few seconds delay when traffic is exposed while the script is loading.

**Comment by brainfucksec** [comment]
About `systemd` unit files, here you can find more information:

https://wiki.archlinux.org/index.php/Systemd#Writing_unit_files
https://www.freedesktop.org/wiki/Software/systemd
https://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by ViRb3** [comment]
Hey, thanks for replying! The direction I'm going is to make sure that kali is torified all the time, even across reboots, with no chance for traffic leaks. Do you have any particular idea how to achieve this? I am trying to get it work using systemd + iptables.
