### ISSUE TITLE
IPv6 disabled

### ISSUE THREAD

**Issue by ViRb3** [brainfucksec/kalitorify#35]
Is there any reason why IPv6 is disabled on `kalitorify -t`?

**Comment by brainfucksec** [comment]
The script uses iptables which set rules for the IPv4 protocol.
iptables is for IPv4 connections, ip6tables is for IPv6 connections. If you want your iptables rules to also apply to IPv6, you have to add them to ip6tables as well.
Furthermore, the IPv6 protocol is not without risk for anonymity:

https://2019.www.torproject.org/docs/faq.html.en#IPv6

So for now, I have preferred to keep the script with the rules for IPv4 only and disabling IPv6.
