### ISSUE TITLE
Your system is not using Tor

### ISSUE THREAD

**Issue by gearcapitan** [brainfucksec/kalitorify#4]
![kali_linux-2018-12-18-10-11-00](https://user-images.githubusercontent.com/13740942/50166747-4616ae00-02ad-11e9-9386-5b04a5c83186.png)

**Comment by brainfucksec** [comment]
Hi gearcapitan, did you reboot the system after installing the program?
Sometimes the transparent proxy configuration or Tor Network they may have problems with a tor node, try simply to restart the program with `--restart` parameter.

**Comment by brainfucksec** [comment]
Added information about '--restart' parameter when tor network error occurred: [commit: c4b0b7922a91aec1c2a1e4325781f4c1b586277f](https://github.com/brainfucksec/kalitorify/commit/c4b0b7922a91aec1c2a1e4325781f4c1b586277f)

**Comment by DJZeman** [comment]
i dont know why but i still have this problem however i upgrade my kali can you help me ?
