### ISSUE TITLE
tor dns not resolving onion addresses

### ISSUE THREAD

**Issue by TheCranston** [brainfucksec/kalitorify#40]
**Describe the bug**
after running 'sudo kalitorify -t' 
launch web browser and attempt to go to an .onion address

**Program error message**
"cannot find host" returned from browser.  regular non-onion sites work fine.  check.torproject.org says browser is connected to tor.  

There are some messages in the syslog about giving up connecting and they seem to be happening when trying to resolve .onion addresses.

current kali linux 2020.1 fresh install in a VM
tried reverting last several commits but no change

**Comment by brainfucksec** [comment]
Hi @TheCranston, if you need to visit the Tor hidden services don't use a Transparent Proxy but use Tor browser, please read here:

https://en.wikipedia.org/wiki/.onion
https://www.whonix.org/wiki/DoNot#Allow_Tor_over_Tor_Scenarios
https://github.com/BrainfuckSec/kalitorify#security
