### ISSUE TITLE
After back to clearnet problem

### ISSUE THREAD

**Issue by hellresistor** [brainfucksec/kalitorify#41]
Hi!
Try your job! Nice job!
I have found issue.
after run command to back to clearnet.
Need restart kali. Firefox stop open webpages and no ping ;)
Cya

**Comment by brainfucksec** [comment]
Ho @hellresistor, thanks for the report.
The latest version presents this problem randomly, I'm working to figure out where the problem is.

**Comment by hellresistor** [comment]
Has I checked maybe needing DNS/host/network service restart (resolvconf, i have tried, but i can not do work using resolvconf package)

**Comment by brainfucksec** [comment]
The problem was due to the new iptables instructions I had inserted in the latest updates.
I modified the instructions and now the program correctly returns to "clearnet" connection.
See last commit for code details.
Thanks again for the report and good work @hellresistor

**Comment by hellresistor** [comment]
Very Good Work! +1
