### ISSUE TITLE
Transparent proxy is not stopping

### ISSUE THREAD

**Issue by jisjose98** [brainfucksec/kalitorify#44]
Transparent proxy is not stopping even after typing kalitorify -c 
After typing the cmd its showing transparent proxy is stopped but unable to vonnect until restarting the system

**Comment by brainfucksec** [comment]
Hi @jisjose98, thanks for the report.
Are you using the latest version of the program?

**Comment by jisjose98** [comment]
Yes it shows that the msg that transparent proxy is stopped but after I try
to browse it shows server is down and I need to restart the PC to start
working

**Comment by brainfucksec** [comment]
@jisjose98 
What do you mean by "server down"? Do you think that this issue is related?

https://github.com/brainfucksec/kalitorify/issues/41

**Comment by jisjose98** [comment]
Yes after running the tool kalitorify it's working perfectly you but as
soon as I stop it i am not able to use internet further unless I restart.

**Comment by brainfucksec** [comment]
Can you show me the output of these commands when you stop kalitorify?
```bash
cat /etc/resolv.conf
cat /usr/share/kalitorify/backups/iptables.backup
sudo iptables -L
```
Do you use some firewall/DNS applications? like UFW, Pi-hole etc?
Thanks for the help

**Comment by jisjose98** [comment]
![15860314005535627611290454059680](https://user-images.githubusercontent.com/55292980/78460547-5c818c80-76df-11ea-8b99-2c83609e1fdd.jpg)
![1586031432983527912963715263554](https://user-images.githubusercontent.com/55292980/78460557-660af480-76df-11ea-8526-3c931348cb68.jpg)

**Comment by brainfucksec** [comment]
Thanks, you need to reset the configurations of these files:

1 - Put your favorite dns in the file `/etc/resolv.conf`:
i.e.:

```
sudo vim /etc/resolv.conf

nameserver 8.8.8.8
nameserver 8.8.4.4
```
(This is an example, I advise you to avoid google DNS)

2 - Go to the "git" folder of kalitorify, if you don't have it anymore, download it again from github, and unistall/reinstall kalitorify:
```
cd kalitorify/
sudo make uninstall
sudo make install
```

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.
