### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by vladstanoiu** [brainfucksec/kalitorify#45]
when i use Kalitorify , i cannot ping , internet works ok.. but when i ping is giving me this:
ping: sendmsg: Operation not permitted

**Comment by brainfucksec** [comment]
Hi, @vladstanoiu, please use a descriptive title for the issue.
ICMP is not possible over Tor:

https://superuser.com/questions/341946/can-i-ping-send-icmp-through-tor
https://2019.www.torproject.org/docs/faq#TransportIPnotTCP
