### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by tokewz** [brainfucksec/kalitorify#46]

**Comment by tokewz** [comment]
How im gonna uninstall this. Not needed anymore, installed tor browser and program didnt work at all. Such as. unusable with vpn.
already removed from /usr/share and main directory, but still command is working.
PLease answer me fast

**Comment by tokewz** [comment]
nvm, checked makefile and created another version what removes everything it installed.

**Comment by brainfucksec** [comment]
Hi @eternityangel. 
You don't need to create another file, you can use the same `Makefile` for uninstall the program, you only need to issue the command:

`sudo make uninstall`

https://superuser.com/questions/264601/removing-installations-done-by-make-install
