### ISSUE TITLE
ip changes everytime!

### ISSUE THREAD

**Issue by azamet90** [brainfucksec/kalitorify#47]
![1](https://user-images.githubusercontent.com/44042178/93144078-e6536e00-f6f1-11ea-842a-d38b0b93845a.png)
![1](https://user-images.githubusercontent.com/44042178/93144108-f5d2b700-f6f1-11ea-994d-722b1a86cc4f.png)
on another tools i see only 1 ip address isnt better?
and the ip address on every 5 minutes or somethings like that changes?
and the ip i see in my terminal and on the site is different?
and how to set it up to use obfs4 bridge?

**Comment by azamet90** [comment]
> ![1](https://user-images.githubusercontent.com/44042178/93144078-e6536e00-f6f1-11ea-842a-d38b0b93845a.png)
> ![1](https://user-images.githubusercontent.com/44042178/93144108-f5d2b700-f6f1-11ea-994d-722b1a86cc4f.png)
> on another tools i see only 1 ip address isnt better?

and the ip address on every 5 minutes or somethings like that changes?

**Comment by brainfucksec** [comment]
Hi @azamet90 
Please see the [Bug Report template](https://github.com/brainfucksec/kalitorify/issues/new/choose)

Anyway you can setup bridges with Tor Browser: https://bridges.torproject.org/

**Comment by brainfucksec** [comment]
Hi @azamet90 
Since it’s been one month, I hope that things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.
