### ISSUE TITLE
DNS over HTTPS or TLS ( DoH or DoT) support

### ISSUE THREAD

**Issue by 5l1v3r1** [brainfucksec/kalitorify#48]
Does kalitorify provides doh or dot ?

**Comment by brainfucksec** [comment]
Hi @5l1v3r1, kalitorify is a script that launch a "Transparent Proxy" this mean that at Operating System level DNS requests are handled by the Tor proxy for avoid DNS leaks, the protocols DoH and DoT are solutions when you are connected with network of your ISP or a public Wi-Fi network for example, for more information I invite you to read here:

https://trac.torproject.org/projects/tor/wiki/doc/TorFAQ#SOCKSAndDNS

**Comment by 5l1v3r1** [comment]
Thank you for the posts. I read them. I decided to use https://github.com/dimkr/nss-tls that one with kalitorify. (nss-tls is an alternative, encrypted name resolving library for Linux distributions with glibc, which uses DNS-over-HTTPS (DoH). The glibc name resolver can be configured through nsswitch.conf(5) to use nss-tls instead of the DNS resolver, or fall back to DNS when nss-tls fails.) It is not proxy-based like dnscrypt-proxy or stubby etc so i think it won't break kalitorify. Do you think this works or am i a super noob about those kind of subjects?

**Comment by brainfucksec** [comment]
The main concept here is that the transparent proxy serves among other things to avoid DNS leaks.
When you contact a server through Tor it receives the DNS request from the exit node, which is not encrypted but the recipient server and the exit node itself cannot know where the initial request comes from.
Theoretically I think it's better to let that Tor network take care of these requests. Not always adding layers is a good practice, in this case as it already happens for DoH and DoT you have to trust the provider that provides the DNS service. This doesn't mean you don't have to test methods to increase security, but make sure you use test environments for this and only switch to main operating systems after you make sure the configuration is valid.

**Comment by 5l1v3r1** [comment]
You are right, and not all the exit nodes  support doh or dot yet, maybe the can think about that in future but i will keep nss-tls working without adding dns adresses and let the tor decides what to do ( use nss-tls instead of the DNS resolver, or fall back to DNS when nss-tls fails.) Sometimes tor exit nodes might be malicious as well (https://www.theregister.com/2014/10/27/tor_exit_node_mashes_malware_into_downloads/). (He said binaries should be delivered through SSL and TLS regardless of whether they were signed.This was critical for users in countries targeted by their governments or for those using the Tor network.) Dictatorial countries like turkey spend millions of dollars to spy on its own people like they paid sandvine group for deep packet inspection etc.. They might be paying people to create spy tor exit nodes as well.

**Comment by brainfucksec** [comment]
Really thanks for the information, I think that this discussion can be helpful to other users.
