### ISSUE TITLE
System is not using Tor - iptables Error

### ISSUE THREAD

**Issue by CertifiedKill** [brainfucksec/kalitorify#5]
Hey I'm getting an error code. This is where it seems to go down. 

[] Set new iptable rules. . .  iptables v1.8.2 (nf_tables): Could't load match 'owner': No such file or directory

Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): unknown option "--dport"
Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): unknown option "--dport"
Try 'iptables -h' or 'iptables --help' for more information.
 iptables v1.8.2 (nf_tables): Could't load match 'owner': No such file or directory

Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): unknown option "--to-ports"
Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): unknown option "--to-ports"
Try 'iptables -h' or 'iptables --help' for more information.
Iptables: Invalid argument. Run 'dmesg' for more information 
iptables v1.8.2 (nf_tables): unknown option "--syn"
Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): unknown option "--to-ports"
iptables v1.8.2 (nf_tables): Could't load match 'state': No such file or directory

Try 'iptables -h' or 'iptables --help' for more information.
 iptables v1.8.2 (nf_tables): Could't load match 'owner': No such file or directory

Try 'iptables -h' or 'iptables --help' for more information.
 iptables v1.8.2 (nf_tables): Chain 'REJECT' does not exsist
Done

==>Check current status of Tor service
[ ok ] Tor service is active

==> Check Tor network settings
Your system is not using Tor:
try restarting the program with 'kalitorify --restart'

**Comment by brainfucksec** [comment]
Hi @CertifiedKill, I'm working on your problem but I need some information:

- Do you use Kali Linux with the default configuration with the root user only?
- Do you have a firewall/ids or other proxy applications installed?

**Comment by brainfucksec** [comment]
@CertifiedKill really thanks for these information, I'm working on your problem.

**Comment by DJZeman** [comment]
Hello, me too i have this problem and i get 134 in terminal after id -u debian-tor

**Comment by brainfucksec** [comment]
@DJZeman I'm working on this problem, thanks for your information is really useful.

**Comment by DJZeman** [comment]
Thx ;)

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by DJZeman** [comment]
thx ;)

**Comment by brainfucksec** [comment]
Try reinstalling tor package:

`sudo apt update && sudo apt full-upgrade -y`
`sudo apt install tor`

**Comment by CertifiedKill** [comment]
Reinstalled the packages. There's no change.

**Comment by brainfucksec** [comment]
I looked for information about this error but I can't find answers, I need time to do some tests.

**Comment by CertifiedKill** [comment]
Alright sounds good, this is a very low priority to me so you can take as much time as you need, update me if you need anything from my end. Good Luck!

**Comment by brainfucksec** [comment]
Hi, @CertifiedKill, 25/5000
I'm working on the problem, but I have some questions:
are you using ipv6 for connections?
have you updated the system with full-upgrade?

**Comment by CertifiedKill** [comment]
I looked through the ifconfig and I think it's telling me I am using IPv6.
Yes i've "full-upgrade"

Could the IPv6 be the issue in this case?

**Comment by CertifiedKill** [comment]
So I went ahead and hopefully disabled it by typing these commands in:

sudo nano /etc/sysctl.conf

and then writing these at the bottom of the file.

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

I went ahead and ran the program and still the same error appears.

**Comment by brainfucksec** [comment]
In the next update I added these instructions for disable IPv6 with sysctl, anyway, I will continue to look for a solution.

**Comment by brainfucksec** [comment]
Hi @CertifiedKill maybe this problem is relative to Raspberry Pi, in particular to libraries of iptables, try to reinstall iptables:
`apt-get install --reinstall iptables`

**Comment by brainfucksec** [comment]
Download the last version, then inside the folder, remove first the previous version:
`git clone https://github.com/brainfucksec/kalitorify
cd kalitorify
sudo make uninstall
`

Then install the new version.

**Comment by CertifiedKill** [comment]
I believe it should work now, currently having bootup issues on my Pi right now but once I get that solved I am confident enough it should work.  Thanks for all the help!

**Comment by brainfucksec** [comment]
Excellent.

**Comment by smoothunit** [comment]
Same issues on both my updated Rpi's, any progress? Have you been able to replicate?
