### ISSUE TITLE
Starting Transparent Proxy

### ISSUE THREAD

**Issue by Banginpadr** [brainfucksec/kalitorify#51]
**Describe the bug**
the script is not working. At first, it was not starting because I think you change your script **torrc.backup** to  **iptables.backup** to **torrc.backup**

**Program error message**
```
:: Starting Transparent Proxy
==> Configure DNS to use Tor's DNSPort
==> Disable IPv6 with sysctl
==> Start Tor service
==> Setup new iptables rules

:: Check current status of Tor service
[ok] Tor service is active

:: Check Tor network settings
[ok] Your system is configured to use Tor

:: Checking your public IP...
IP Address details:


[ok] Transparent Proxy activated, your system is under Tor

```

**Shell used**
bash

**Additional context**
I think some how the script got miss up with different names. can you please help me? also it I didn't install this in my home folder but at **downloads** as you also can see I'm not getting a **Checking your public IP**

**Comment by sophiya02** [comment]
I am facing with same problem . .... Have you solved it now !!!!! ... Also when firefox is showing "server not found error"  how to fix this ....

**Comment by brainfucksec** [comment]
Hi guys, please see: ISSUE #52
