### ISSUE TITLE
Error with torrc file (/etc/tor/torrc) and torrc.backup

### ISSUE THREAD

**Issue by mguzman999** [brainfucksec/kalitorify#52]
**Describe the bug**
When I start the transparent proxy and then i reset the iptables it says me that the file torrc.backup doesnt exist.

**Program error message**
:: Stopping Transparent Proxy
==> Restore default iptables rules
==> Stop tor service
==> Restore /etc/resolv.conf file with default DNS
==> Enable IPv6
==> Restore default '/etc/tor/torrc'
cp: no se puede efectuar `stat' sobre '/usr/share/kalitorify/backups/torrc.backup': No existe el fichero o el directorio

[-] Transparent Proxy stopped

**Screenshots**
![kalitorify](https://user-images.githubusercontent.com/73953455/102419608-685c7700-4000-11eb-89d1-6cc85405da5f.PNG)

**Shell used**
bash

**Comment by brainfucksec** [comment]
Hi @mguzman999, thanks for the report.
There is a problem with the last `tor` package, I'm working for the fixl, I will update this post with progress.

**Comment by brainfucksec** [comment]
Fixed, please download [latest release](https://github.com/brainfucksec/kalitorify/releases)
For those who have messed up the `torrc` file, copy it from the kalitorify directory:

```bash
cd kalitorify/
sudo cp -vf data/torrc.default /etc/tor/torrc
```

If there are still problems reinstall the `tor` package and then kalitorify.

**Comment by shownb** [comment]
why this thing happened?

**Comment by mguzman999** [comment]
The problem it's solved when i reinstall kalitorify, thank you to solve the problem.
