### ISSUE TITLE
Installed kalitorify - now no internet

### ISSUE THREAD

**Issue by superclown2** [brainfucksec/kalitorify#53]
I installed kalitorify 1.24.3 into kali linux on a VirtualBox virtual machine but now there is no Internet access from it.  When it checks my public IP address the IP Address details are blank. Is there a way out of this please?

after command kalitorify -c I get message: cannot stat '/usr/share/kalitorify/backups/torrc.backup': No such file or directory. There is a file in that directory though called resolv.conf.backup which contains a single line 
nameserver 127.0.0.1

**Comment by brainfucksec** [comment]
Hi @superclown2, I'm working for a fix please see: [ISSUE #52](https://github.com/brainfucksec/kalitorify/issues/52)
