### ISSUE TITLE
Question.  Where to add a custom tor param

### ISSUE THREAD

**Issue by AkliOnet** [brainfucksec/kalitorify#57]
I want to add the line ExitNodes {xx} StrictNodes 1 in the torrc file but it always overwritten.

**Comment by brainfucksec** [comment]
Hi @AkliOnet, try to add this parameter to the [data/torrc](https://github.com/brainfucksec/kalitorify/blob/master/data/torrc) file then install kalitorify with `make install` command.
Maybe you already know that this is a critical parameter for Tor, for other information read here:

https://2019.www.torproject.org/docs/tor-manual.html#ExcludeExitNodes

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope that things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.
