### ISSUE TITLE
Your system is not using Tor (again, still)

### ISSUE THREAD

**Issue by windowshopr** [brainfucksec/kalitorify#59]
**Describe the bug**
Running sudo kalitorify -t gives…

**Program error message**
[!] Your system is not using Tor

try another Tor circuit with ‘kalitorify —restart’

**Screenshots**
No screenshots necessary. 

**Other network proxies/firewalls or DNS applications installed**
No firewall (that I’m aware of? Unless one is included in Kali’s fresh install.) I’m currently running a NordVPN connection, maybe that has something to do with it?

**Shell used**
Bash. 

**Additional context**
Kali 2021.3, all updated packages, and ran your install steps perfectly, just not connecting to a tor node. I’ve read the previous issue posts regarding this, but they didn’t resolve the issue for me/they were closed due to lack of response from the user, so I’m hoping to get this figured out for my case. Thanks!

**Comment by windowshopr** [comment]
I turned off/disconnected from/disabled firewall in NordVPN and also set kill switch to disabled, so basically took NordVPN out of the equation, still same issue. Tried a reinstall of kalitorify as well.

**Comment by brainfucksec** [comment]
Hi @windowshopr.
You need to disable the VPN not only the kill switch.

**Comment by windowshopr** [comment]
@brainfucksec i did. Maybe my explanation wasn’t that great lol I disconnect from my VPN and shut down the program entirely. Before I did that, I disabled the firewall and kill switch settings. The VPN program isn’t even running, still go the same error.

**Comment by brainfucksec** [comment]
What firewall do you use? if you use the iptables rules you need to restart the `iptables.service` after a change.
Check the `/etc/resolv.conf` file, maybe is a DNS problem.
Check `/etc/tor/torrc` file, this is the default: https://github.com/brainfucksec/kalitorify/blob/master/data/torrc.default
I don't know the NordVPN application but maybe the application modifies some Tor related files if you use their Tor nodes.

Check if `tor` service works correctly:

```
sudo systemctl start tor

tor
```

Check that there are no errors in the output of the command.

https://tor.stackexchange.com/questions/12341/how-to-properly-start-tor-service

**Comment by windowshopr** [comment]
Ok I’ve narrowed it down. 

`sudo kalitorify -c`
`sudo systemctl stop tor`
`nordvpn d`

So this shuts down all tor and NordVPN connections. Then I just run 

`sudo kalitorify —tor`

And it connects. This is all after a restart from installation yes. 

Only problem now is, how can I ensure that I’m connected to my NordVPN while using kalitorify? From here, with kalitorify running, I try to run 

`nordvpn connect`

which connects to a vpn, however if I have kalitorify running already, I’m unable to connect to any webpage. I’m new to kali so I don’t know anything about what iptables are or what programs utilize what from it. Does this help at all? What should I try to modify so that I can be connected to vpn WHILE kalitorify is runnin? Thanks!

**Comment by windowshopr** [comment]
I see #26 after a quick search. Not sure I follow the details there, it’s always recommended to use tor from behind a vpn so would be good to figure this out

**Comment by brainfucksec** [comment]
Obviously I can't provide support for applications outside kalitorify, in this case the program works and I'm glad you solved the problem.

About Tor and VPN I recommend the [Tor Project FAQ ](https://support.torproject.org/faq/faq-5/) if you have not already read.

Good work.
