### ISSUE TITLE
[Question] Is there kalitorify for Ubuntu ?

### ISSUE THREAD

**Issue by kevinadhiguna** [brainfucksec/kalitorify#60]
Hi, I understand this is for Kali Linux but I want to know if this tool works well in Ubuntu or not, or even if there's a repo/tool with the same functionality for Ubuntu.

Thank you.

**Comment by brainfucksec** [comment]
Hi @kevinadhiguna, you can try [nipe](https://github.com/htrgouvea/nipe) or you can do a search using the filter "topic" [transparent-proxy](https://github.com/topics/transparent-proxy).

**Comment by kevinadhiguna** [comment]
I got it, thanks @brainfucksec !
