### ISSUE TITLE
100% Package Loss

### ISSUE THREAD

**Issue by lcsvcn** [brainfucksec/kalitorify#61]
After running `sudo kalitorify -t` I am receiving 100% package loss:
  
![image](https://user-images.githubusercontent.com/6011385/155381881-2a555f57-5f26-4056-a8d3-c1f76a45805a.png)

if I run `sudo kalitorify -c`, it gets normal:

![image](https://user-images.githubusercontent.com/6011385/155381655-d11cc734-5ebf-442d-8777-a781831aefd4.png)

What is happening? Am I missing sth?

**Comment by brainfucksec** [comment]
Hi @lcsvcn 
Please see: #45
