### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dotslashsuperstar** [brainfucksec/kalitorify#63]
Looks like you have a great implementation. I am using the iptables rules from tor wiki and was just wondering if you knew if it's just me or scans like nmap return really inaccurate results like all ports open. Like nmap 'iphere'.  Ping, and traceroute dont work as well afaik since its not tcp. Wget and browser work.  Any ideas of programs for scans and networking that work/dont work? Thanks

**Comment by brainfucksec** [comment]
Hi @dotslashsuperstar, about `ping` and `traceroute` commands see: #45
For `nmap` results maybe it depends on the server you are testing, you should refer to nmap`s documentation for that.
