### ISSUE TITLE
"Ip api"-address in check_ip() doesn't work

### ISSUE THREAD

**Issue by MrOffSec** [brainfucksec/kalitorify#64]
The first ip api address in the list of apis in [check_ip()](https://github.com/brainfucksec/kalitorify/blob/master/kalitorify.sh#L270) doesn't work for me any longer.:
```
https://ipleak.net/json/
```

If I start kalitorify with the command 
```
sudo kalitorify -t
```
It gives me an error:
    "Your system is not using tor!"

So I removed this address from the list and now the program works perfectly fine. If other users also experiencing this, maybe this address should be removed in general. 

I use no proxies myself, no bridges, nothing.

Default shell from kali linux (Terminal) was used.

**Comment by brainfucksec** [comment]
Hi @MrOffSec
I need to check and update the list of the links in the `check_ip` function, thanks.
