### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fahadph1** [brainfucksec/kalitorify#66]
after giving `make install` i got this error

install -Dm644 README.md /usr/share/doc/kalitorify/README.md
install -Dm755 kalitorify.sh /usr/bin/kalitorify
mkdir -p /usr/share/kalitorify/data
mkdir -p /var/lib/kalitorify/backups
install -Dm644 data/* /usr/share/kalitorify/data

**Comment by brainfucksec** [comment]
Hi @fahadph1 
Is not an error is the normal output of the command, informs you of the operations performed and the path to the installed files.
See: https://www.gnu.org/software/make/
