### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 10ox** [brainfucksec/kalitorify#68]
![5059bc5a-0938-4198-88c9-e6a8320c2d3d.jpg](https://user-images.githubusercontent.com/104843175/192780087-9752cf46-d085-4660-ba0d-5828bf85e550.jpg)
I'm use tool and sites not open how stopp this tool

**Comment by brainfucksec** [comment]
Hi @10ox, with this information only, I can't help you, did you read the README before running the program?

https://github.com/brainfucksec/kalitorify#usage 

Check the steps in the section "Before starting kalitorify"
