### ISSUE TITLE
just a question 

### ISSUE THREAD

**Issue by d0lla1976** [brainfucksec/kalitorify#69]
I use kalitorify all the time..
I have been doing some testing and my question is,
 Does kalitorify run all my traffic including my terminal information through kalitorify?

**Comment by brainfucksec** [comment]
Hi @d0lla1976, what do you mean exactly for "terminal information", the terminal emulator is an application like the others.

**Comment by d0lla1976** [comment]
yeah brother i get that..
I guess what i'm asking is, 
If i run an nmap scan against a target and i have kalitorify running will the scan i'm running in the terminal  go through tor (kalitorify)?
Once kalitorify is activated does every outside connection I attempt run through tor (kalitorify)?

BTW. I really appreciate your work and you taking the time to answer my questions..

**Comment by Zbergen-cli** [comment]
@d0lla1976, Yes, everything goes through Tor, but there is no stream isolations and will not be. That is, after enabling kalitorify, the likelihood that all connections will use the same ip address is very high. If you use the tor browser you will also get tor over tor which will also not be fixed.

**Comment by brainfucksec** [comment]
The topics that @Zbergen-cli has excellently explained to you are all presents in the `README` (see: the [Security](https://github.com/brainfucksec/kalitorify#security) section).
You can delve into the various topics from the indicated sources.

Also see the basics, like:

https://en.wikipedia.org/wiki/Proxy_server

https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TransparentProxy
