### ISSUE TITLE
Apt not not working!

### ISSUE THREAD

**Issue by chnz2k** [brainfucksec/kalitorify#7]
i found that apt is not compatible with kalitorify , wich give th following problem xD 
Err:1 http://deb.parrotsec.org/parrot parrot InRelease
  403  Forbidden [IP: 104.XX.125.XX 80]
Get:2 http://packages.microsoft.com/repos/vscode stable InRelease [3,181 B]
Get:3 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [87.0 kB]
Reading package lists... Done       
E: Failed to fetch http://deb.parrotsec.org/parrot/dists/parrot/InRelease  403  Forbidden [IP: 104.XX.125.XX 80]

so some debs can connect others cant  .

**Comment by brainfucksec** [comment]
Those repositories are not of Kali Linux but of Parrot OS.
