### ISSUE TITLE
System is not using Tor

### ISSUE THREAD

**Issue by TheJoeMan1** [brainfucksec/kalitorify#71]
I have download Kalitorify on VirtualBox and as dual boot OS with windows on my laptop both gave me same error "System is not using tor."

Kalitorify Version: 1.29.0
Kernel Version: 6.5.0-kali2-amd64

note:

I have downloaded tor. 
I restarted. 
I added tor bridges to /etc/tor/torrc and removed it again since it didn't work as well.

I need some help :)

**Comment by JawadPy** [comment]
simple solution, uninstall

**Comment by brainfucksec** [comment]
Hi @TheJoeMan1, thanks for the advice.
Unfortunately, for the moment kalitorify does not implement the use of tor bridges.
Thank you very much for the report, it is already on the priority list for the next versions.

Regarding your problem, the `/etc/tor/torrc` file should not be changed after starting kalitorify.
